security:
    encoders: 
      
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: false 
            lazy: true
            provider: app_user_provider
            entry_point: form_login
            
            form_login:
                 login_path: app_login
            
            custom_authenticator: App\Security\MainAuthenticator

            

            logout:
                path: app_logout
            
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
            
    enable_authenticator_manager: true 

    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/profile, roles: ROLE_USER }

    role_hierarchy: 
        ROLE_CHEFPARC: ROLE_USER
        ROLE_DIRECTOR: ROLE_USER
        ROLE_SECRETARY: ROLE_USER
        ROLE_ADMIN: 
            - ROLE_SECRETARY   
            - ROLE_CHEFPARC 
            - ROLE_DIRECTOR

    